CREATE TABLE agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE voting_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id BIGINT NOT NULL UNIQUE,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_session_agenda FOREIGN KEY (agenda_id) REFERENCES agenda(id)
);

CREATE TABLE vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id BIGINT NOT NULL,
    associate_id VARCHAR(255) NOT NULL,
    cpf VARCHAR(14),
    vote VARCHAR(3) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_vote_agenda FOREIGN KEY (agenda_id) REFERENCES agenda(id),
    CONSTRAINT uk_vote_associate_agenda UNIQUE (agenda_id, associate_id)
);

CREATE INDEX idx_vote_agenda_id ON vote(agenda_id);
CREATE INDEX idx_session_agenda_id ON voting_session(agenda_id);
